// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wpulntxwrofxtmiknumk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndwdWxudHh3cm9meHRtaWtudW1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ0NTI0NzAsImV4cCI6MjA1MDAyODQ3MH0.Zj-w4iiFOph-VMNRb4iE-uMSvt75B5StfREfQ32UjeY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);